version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"

  ngrok:
    image: ngrok/ngrok:latest
    command: http backend:8080
    environment:
      - NGROK_AUTHTOKEN=2mVKjqgpJHHt4Vs1j81cOvrlLtT_7nxw1KznVRv6P6ajU7Kn8
    ports:
      - "4040:4040"
